import "fontsource-libre-baskerville"
import "fontsource-libre-baskerville/400.css"
import "fontsource-libre-baskerville/700.css"
import "fontsource-poppins"
import "fontsource-poppins/400.css"
import "fontsource-poppins/700.css"
import "./src/styles/app.css"
